name: WeaponMaster
description: Weapon plugin realized on demand for a client
version: 1.0
api-version: 1.13

main: com.dandan2611.weaponmaster.WeaponMaster

commands:
  weapon:
    permission: weapon.use